### ISSUE TITLE
The Environmental Entities section loads slowly - need an indicator

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/swsi-story-sp-entities#10]
The Environmental Entities section loads slowly because the embedded page loads slowly due to large data file (?).   It would be nice to embed a spinner or other indicator that the page is loading.  Maybe this needs to be done in the original visualization?  Otherwise, add text to the story indicating that it may take some time to load.

**Comment by jurentie** [comment]
This page now loads fine. The iframe has been replaced with an image and a popup with a link to the visualization.
