### ISSUE TITLE
Need to decide link color for black text

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/swsi-story-sp-entities#13]
The story now uses underlined white text for links on pages where text is white.  This seems to read well.  However, some pages that have black text still use blue for links, rather than, for example, underlined black text.  The blue looks OK but given the other change is a bit in consistent.  For stories that include map elements, a general standard might be to just use underlines for links and use colored text to match the map legend on pages with maps or other visualizations with color legend.

**Comment by smalers** [comment]
Now that external links have the icon, it may be easier to just use underline for links, similar to white text.  Therefore links would not be blue.  Need to discuss with Justin and Kristen.

**Comment by jurentie** [comment]
Changed link color to black on regular pages, with underline.
commit: 9ed5c67
