### ISSUE TITLE
Add background map selection tool, scale, and lat/long indicator

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/swsi-story-sp-entities#20]
The IPPs story has recently been updated to have background map selector, scale, and lat/long indicator on most map pages.  The decision was made to place these controls on the left so as to not interfere with the data popups and legend.  This seems to work well.  Therefore, Kristin should look over the latest IPP story and then work with Justin to implement similar features for the Entities.

Also need to make sure that the maps with animation control layout properly with the various map controls.

**Comment by jurentie** [comment]
Maps now have selection tool, scale, and lat/long indicator 
532f089
