### ISSUE TITLE
Update upload script to package site for soutplattebasin.com

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/swsi-story-sp-entities#22]
The upload script works well for Amazon S3 upload.  However, the current approach does not produce a cache-busting result that can be installed on southplattebasin.com.  Need to update to make it work.

**Comment by smalers** [comment]
Added a new script create-upload-site.sh to prep the website for upload in the tmp-build folder, but don't upload.  Then the run-http-server-8000.sh script can be run with ANY command line parameter to view the prepped site.  The build-util/README.md file explains the scripts.  Justin should be able to run the create script and then upload the contents to southplattebasin.com.  He can also further modify the script to create a zip file if that helps, but will depend on whether that capability is in Cygwin or Git Bash.

**Comment by jurentie** [comment]
Updated copy-to-owf-amazon.sh to also zip files when set to prep-upload. Uploaded contents to southplattebasin.com
