### ISSUE TITLE
Feedback from Joe Frank

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/swsi-story-sp-entities#26]
At the Oct 9 South Platte Roundtable meeting Joe Frank suggested that the section showing urban/ag land change should link to the OWF animations on irrigated lands changes.  This did not make sense as the main part of the visualization because the division map is not clear enough and showing a district might be too localized.

I suggest adding a link from the "Changes in Agricultural Lands" to the OWF [Colorado Irrigated Acreage visualization](http://viz.openwaterfoundation.org/co/co-irrigated-ag-animation/index.html).

**Comment by kswaim** [comment]
Link added to "Changes in Agricultural Lands" page.
